In [5]:
#A* search (Heuristic function)
from math import sqrt
from numpy import zeros        

In [52]:
def heuristic(a,b, objective = [-1,-1]):
    h = zeros((a,b))
    for i in range(len(h[0,:])):
        for j in range(len(h[:,0])):
            h[j][i] = sqrt((i-objective[1])**2 + (j-objective[0])**2)
    print h
    return h

def initialize_map(a, b, player = [0,0], objective = [-1,-1]):
    vals = zeros((a,b))
    vals[player[0],player[1]] = 1
    vals[objective[0],objective[1]] = 2
    print vals
    return vals

#def difference(a, b):
    

def possible_moves(frontier, field, explored = 0):
    for position in frontier:
        possibilities = []
        x, y = position[0], position[1]
        #checking if it falls off the map or not
        if x-1 >= 0:                    possibilities.append([(x-1), y])  #Checks if it can move left
        if x+1 < len(field[:,0]):       possibilities.append([(x+1), y])  #Checks if it can move right
        if y-1 >= 0:                    possibilities.append([x, (y-1)])  #Checks if it can move up
        if y+1 < len(field[0,:]):       possibilities.append([x, (y+1)])  #Checks if it can move down
        return possibilities
#her[:,0] #Column [up down]
#her[0,:] #rows <->
#her[down, right]

In [55]:
#initialize map and function
inp = list(map(int, raw_input().split()))
frontier = [[0,0]]
explored = []
objective = [2,4]
player = [0,0]
vals = initialize_map(inp[0], inp[1], player, objective)
her = heuristic(inp[0], inp[1], objective)

5 6
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 4.47213595  3.60555128  2.82842712  2.23606798  2.          2.23606798]
 [ 4.12310563  3.16227766  2.23606798  1.41421356  1.          1.41421356]
 [ 4.          3.          2.          1.          0.          1.        ]
 [ 4.12310563  3.16227766  2.23606798  1.41421356  1.          1.41421356]
 [ 4.47213595  3.60555128  2.82842712  2.23606798  2.          2.23606798]]


In [35]:

x = possible_moves(frontier, vals)

for element in x: 
    frontier.append(element)
print frontier

[[0, 0], [1, 0], [0, 1]]


TypeError: set expected at most 1 arguments, got 3

In [56]:
abc = [[[0,0],[0,1]],[[1,1][0,1]]]

TypeError: list indices must be integers, not tuple